# Generated by Django 3.2 on 2023-03-30 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
