# Generated by Django 3.2 on 2023-04-02 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
